config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/dockers/images', to: 'dockers#get_dh_images' 
  get 'dockers/list'
  get '/dockers/schedule-test', to: 'dockers#schedule_test'
  get 'tests/schedule', to: 'tests#schedule'
  root 'welcome#index'
  resources :runningtests
  resources :dockers
  resources :tests
  resources :influxdbs
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/runningtest.rb
class Runningtest < ApplicationRecord
end

app/controllers/runningtests_controller.rb
class RunningtestsController < ApplicationController

  def new
  end

  def index
    @runningtests = Runningtest.all.order("id ASC")
  end

  def edit
  end


  def update
    results_hash = {
        "status" => params[:test_results][:status],
        "details" => params[:test_results]
    }
    @runningtest=Runningtest.find(params[:id])
    @runningtest.update(results_hash)
  end

  def destroy
    @runningtest=Runningtest.find(params[:id])
    helpers.stop_container(@runningtest, Docker.find(@runningtest.docker_host_id))
    @runningtest.destroy
    redirect_to runningtests_path
  end

  def show
  end

  def create
  end

  private
    def runningtest_params
        params.require(:runningtest).permit(:container_name, :docker_host, 
        :influxdb_adapter_id, :test_params, :status, :details)
    end

  
end

app/views/runningtests/edit.html.erb
<br>
<br>

<div class="new_resource_container">
  <div class="new_resource_caption">
    <p>Edit test settings</p>
  </div>


</div>

app/views/runningtests/index.html.erb
<div class="header">
  <%= link_to "Schedule a test", tests_path, class: "actions" %>
</div>

<div class="container">
  <table class="responsive-table">
    <caption>Running tests list</caption>
    <thead>
       <tr>
          <th scope="col">ID</th>
          <th scope="col">Container name</th>
          <th scope="col">Docker host</th>
          <th scope="col">InfluxDB adapter</th>
          <th scope="col">Test parameters</th>
          <th scope="col">Status</th>
          <th scope="col">Details</th>
          <th scope="col">Stop test</th>
       </tr>
    </thead>
    <tfoot>
      <tr>
        <td></td>
      </tr>
    </tfoot>
    <tbody>
      <% @runningtests.each do |runningtest| %>
        <tr>
          <th scope="row"><%= link_to runningtest.id.to_s, runningtest_path(runningtest) %></th>
            <td data-title="Container name"><%= runningtest.container_name %></td>
            <td data-title="Docker host"><%= Docker.find(runningtest.docker_host_id).docker_host_name %></td>
            <td data-title="InfluxDB adapter"><%= Influxdb.find(runningtest.influxdb_adapter_id).adapter_name %></td>
            <td data-title="Test parameters" style="text-align:left"><pre>
            <!-- Begin of the JSON output -->
                <%= JSON.pretty_generate(runningtest.test_params) %>
            <!-- End of the JSON output -->
             </pre></td>
            <td data-title="Status"><%= runningtest.status %></td>
            <td data-title="Details" style="text-align:left"><pre>
            <!-- Begin of the JSON output -->
                <%= JSON.pretty_generate(runningtest.details) %>
            <!-- End of the JSON output -->
            </pre></td>
            <td data-title="Stop test"><%= link_to 'Stop', runningtest_path(runningtest), method: :delete,
                          data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>