config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/dockers/images', to: 'dockers#get_dh_images' 
  get 'dockers/list'
  get '/dockers/schedule-test', to: 'dockers#schedule_test'
  get 'tests/schedule', to: 'tests#schedule'
  root 'welcome#index'
  resources :runningtests
  resources :dockers
  resources :tests
  resources :influxdbs
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/influxdb.rb
class Influxdb < ApplicationRecord
  has_many :tests
end

app/controllers/influxdbs_controller.rb
class InfluxdbsController < ApplicationController

  def new
  end



  def index
    @influxdbs=Influxdb.all.order("id ASC")
  end

  def edit
    @influxdb=Influxdb.find(params[:id])
  end


  def update
    @influxdb=Influxdb.find(params[:id])

    if @influxdb.update(influxdb_params)
      redirect_to @influxdb
    else
      render 'edit'
    end

  end

  def destroy
    @influxdb=Influxdb.find(params[:id])
    @influxdb.destroy
    redirect_to influxdbs_path
  end

  def show
    @influxdb= Influxdb.find(params[:id])
  end

  def create
    @influxdb = Influxdb.new(influxdb_params)     
    @influxdb.save
    redirect_to @influxdb
  end
          
  private
    def influxdb_params
        params.require(:influxdb).permit(:adapter_name,:host,:port,
        :username,:password,
        :db_name,:protocol)
      #render plain: params[:docker].inspect
    end

end

app/views/influxdbs/edit.html.erb
<br>
<br>

<div class="new_resource_container">
  <div class="new_resource_caption">
    <p>Edit InfluxDB adapter configuration</p>
  </div>

  <%= form_with model: @influxdb, local: true, method: "patch", :action => 'update' do |form| %>
    <table class="new_resource_table" border="none">
      <tr>
        <td>InfluxDB adapter name</td>
        <td><%= form.text_field(:adapter_name, :class=>"form_input", value: @influxdb.adapter_name) %></td>
      </tr>
      <tr>
        <td>FQDN or IP address</td>
        <td><%= form.text_field(:host, :class=>"form_input", value: @influxdb.host) %></td>
      </tr>
        <tr>
        <td>TCP port</td>
        <td><%= form.text_field(:port, :class=>"form_input", value: @influxdb.port) %></td>
      </tr>
        <tr>
        <td>Protocol</td>
        <td><%= form.text_field(:protocol, :class=>"form_input", value: @influxdb.protocol) %></td>
      </tr>
        <tr>
        <td>Database name</td>
        <td><%= form.text_field(:db_name, :class=>"form_input", value: @influxdb.db_name) %></td>
      </tr>
        <tr>
        <td>User name</td>
        <td><%= form.text_field(:username, :class=>"form_input", value: @influxdb.username) %></td>
      </tr>
        <tr>
        <td>User password</td>
        <td><%= form.text_field(:password, :class=>"form_input", value: @influxdb.password) %></td>
      </tr>
    </table>
    <p>
      <%= form.submit("Update settings",:class=>"form_button") %>
    </p>
  <% end %>
</div>

app/views/influxdbs/index.html.erb
<div class="header">
  <%= link_to "Create InfluxDB adapter", new_influxdb_path, class: "actions" %>
</div>

<div class="container">
  <table class="responsive-table">
    <caption>InfluxDB hosts list</caption>
    <thead>
       <tr>
          <th scope="col">ID</th>
          <th scope="col">Adapter name</th>
          <th scope="col">Host</th>
          <th scope="col">Port</th>
          <th scope="col">Protocol</th>
          <th scope="col">Database name</th>
          <th scope="col">Edit host settings</th>
          <th scope="col">Delete host</th>
       </tr>
    </thead>
    <tfoot>
      <tr>
        <td></td>
      </tr>
    </tfoot>
    <tbody>                  
      <% @influxdbs.each do |influxdb| %>
        <tr>
          <th scope="row"><%= link_to influxdb.id.to_s, influxdb_path(influxdb) %></th>
            <td data-title="InfluxDB adapter name"><%= influxdb.adapter_name %></td>
            <td data-title="Host"><%= influxdb.host %></td>
            <td data-title="Port"><%= influxdb.port %></td>
            <td data-title="Protocol"><%= influxdb.protocol %></td>
            <td data-title="Database name"><%= influxdb.db_name %></td>
            <td data-title="Edit host settings"><%= link_to 'Edit', edit_influxdb_path(influxdb) %></td>
            <td data-title="Delete host"><%= link_to 'Delete', influxdb_path(influxdb), method: :delete,
                          data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/influxdbs/new.html.erb
<br>
<br>

<div class="new_resource_container">
  <div class="new_resource_caption">
    <p>Create InfluxDB adapter</p>
  </div>

  <%= form_with scope: :influxdb, url: influxdbs_path, local: true do |form| %>
    <table class="new_resource_table" border="none">
      <tr>
        <td>InfluxDB adapter name</td>
        <td><%= form.text_field(:adapter_name, :class=>"form_input", value: 'InfluxDB JMeter') %></td>
      </tr>
      <tr>
        <td>FQDN or IP address</td>
        <td><%= form.text_field(:host, :class=>"form_input", value: '127.0.0.1') %></td>
      </tr>
        <tr>
        <td>TCP port</td>
        <td><%= form.text_field(:port, :class=>"form_input", value: '8086') %></td>
      </tr>
        <tr>
        <td>Protocol</td>
        <td><%= form.text_field(:protocol, :class=>"form_input", value: 'HTTP') %></td>
      </tr>
        <tr>
        <td>Database name</td>
        <td><%= form.text_field(:db_name, :class=>"form_input", value: 'jmeter') %></td>
      </tr>
        <tr>
        <td>User name</td>
        <td><%= form.text_field(:username, :class=>"form_input", value: 'tiger') %></td>
      </tr>
        <tr>
        <td>User password</td>
        <td><%= form.text_field(:password, :class=>"form_input", value: 'user') %></td>
      </tr>
    </table>
    <p>
      <%= form.submit("Save configuration",:class=>"form_button") %>
    </p>
  <% end %>
</div>

app/views/influxdbs/show.html.erb
<br>
<br>

<div class="new_resource_container">
  <div class="new_resource_caption">
    <p>InfluxDB adapter configuration summary</p>
  </div>


    <table class="new_resource_table" border="none">
      <tr>
        <td>Adapter name</td>
        <td><%= @influxdb.adapter_name %></td>
      </tr>
      <tr>
        <td>FQDN/IP</td>
        <td><%= @influxdb.host %></td>
      </tr>
      <tr>
        <td>TCP port</td>
        <td><%= @influxdb.port %></td>
      </tr>
      <tr>
        <td>Protocol</td>
        <td><%= @influxdb.protocol %></td>
      </tr>
      <tr>
        <td>User name</td>
        <td><%= @influxdb.username %></td>
      </tr>
      <tr>
        <td>User password</td>
        <td><%= @influxdb.password %></td>
      </tr>
      <tr>
        <td>Database name</td>
        <td><%= @influxdb.db_name %></td>
      </tr>
    </table>
    <%= link_to 'Back to the adapters list', influxdbs_path, class: "header" %>
</div>