config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get '/dockers/images', to: 'dockers#get_dh_images' 
  get 'dockers/list'
  get '/dockers/schedule-test', to: 'dockers#schedule_test'
  get 'tests/schedule', to: 'tests#schedule'
  root 'welcome#index'
  resources :runningtests
  resources :dockers
  resources :tests
  resources :influxdbs
 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/docker.rb
class Docker < ApplicationRecord
end

app/controllers/dockers_controller.rb
class DockersController < ApplicationController

  def new
#    render plain: params[:host].inspect
  end


  def schedule_test
    require 'socket'

    @docker=Docker.find(params[:docker_host][:id])
    @test_obj=Test.find(params[:id])
    @influxdb_obj=Influxdb.find(params[:influxdb_adapter_id])

    @container_name=params[:docker_image_name].gsub(/:|\//,'_')+'_'+Time.now.to_f.to_s.gsub('.','')

    ip_address = Socket.ip_address_list.find { |ai| ai.ipv4? && !ai.ipv4_loopback? }.ip_address

    @schedule_params={
      "HostConfig": {
        "Memory": @test_obj.ram * 1000000, # Memory is using bytes
#        "CpusetCpus": @test_obj.cpu_cores.to_s,
        "AutoRemove": true
      },
      "Image": params[:docker_image_name],
      "User": @test_obj.user_id,
      "Env": [
        "rails_host=#{ip_address}",
        "rails_port=3100",
        "tests_repo=#{@test_obj.git_repo_url}",
        "test_type=#{@test_obj.test_type}", # the name of the test will be used as test type in InfluxDB JMeter adapter
        "current_build_number=#{params[:build_number]}",
        "keep_container_running=#{params[:keep_container_running]}",
        "project_id=#{@test_obj.project_id}",
        "env_type=#{@test_obj.env_type}",
        "lg_id=#{@container_name}",
        "influx_protocol=#{@influxdb_obj.protocol}",
        "influx_host=#{@influxdb_obj.host}",
        "influx_port=#{@influxdb_obj.port}",
        "influx_db=#{@influxdb_obj.db_name}",
        "influx_username=#{@influxdb_obj.username}",
        "influx_password=#{@influxdb_obj.password}"
        ]
    }

    if params[:delete_container_after_exit] != "1"
        @schedule_params[:HostConfig][:AutoRemove] = false
    end

    schedule_params_public = @schedule_params.deep_dup
    schedule_params_public[:Env].find { |line| line =~ /influx_password/ }.replace( "influx_password=*******" )
    @runningtest = Runningtest.new(
        "container_name": @container_name,
        "docker_host_id": @docker.id,
        "influxdb_adapter_id": @influxdb_obj.id,
        "test_params": schedule_params_public,
        "status": "running",
        "details": "N/A"
    )
    @runningtest.save

    @schedule_params[:Env].append("running_test_id=#{@runningtest.id}")
    @start_params={}
    @test_attributes = helpers.schedule_test(@test_obj,@docker,@influxdb_obj,@schedule_params,@start_params,@container_name)

    @request_params={
      "docker_host['id']" => params[:docker_host][:id],
      "build_number" => params[:build_number],
      "docker_image_name" => params[:docker_image_name],
      "id" => params[:id],
      "influxdb_adapter_id" => params[:influxdb_adapter_id]
    }
    @request_params.to_json

    render 'schedule_test'
  end


  def get_dh_images
    require 'json'

    @docker=Docker.find(params[:id])
    @dh_images=JSON.parse(helpers.get_images(@docker))
    
  end

  def index
    @dockers=Docker.all.order("id ASC")
  end

  def edit
    @docker=Docker.find(params[:id])
  end


  def update
    @docker=Docker.find(params[:id])

    if @docker.update(docker_params)
      redirect_to @docker
    else
      render 'edit'
    end

  end

  def list
    @dockers=Docker.all
  end

  def destroy
    @docker=Docker.find(params[:id])
    @docker.destroy
    redirect_to dockers_path
  end

  def show
    @docker= Docker.find(params[:id])
  end

  def create
    @docker = Docker.new(docker_params)     
    @docker.save
    redirect_to @docker
  end
          
  private
    def docker_params
        params.require(:docker).permit(:docker_host_name,:docker_host_fqdn,:docker_host_ram,
        :docker_host_cpu,:docker_host_disk_space,
        :docker_host_location,:docker_host_network_interface_throughput,
        :docker_host_provider_type,:docker_host_api_key,:docker_host_api_cert)
      #render plain: params[:docker].inspect
    end

end

app/helpers/dockers_helper.rb
module DockersHelper

  def get_images(docker_obj)
    # curl -k https://10.0.2.15:2376/images/json --cert ~/.docker_obj/cert.pem --key ~/.docker_obj/key.pem --cacert ~/.docker_obj/ca.pem
    return http_req(docker_obj.docker_host_fqdn,docker_obj.docker_host_api_key,docker_obj.docker_host_api_cert,'/images/json')
  end

  def schedule_test(test_obj,docker_obj,influxdb_obj,schedule_params,start_params,container_name)

    Rails.logger.info "Scheduling docker container with the following params: #{schedule_params}"
    Rails.logger.info http_req(docker_obj.docker_host_fqdn,docker_obj.docker_host_api_key,docker_obj.docker_host_api_cert,'/containers/create?name='+container_name,schedule_params)

    Rails.logger.info "Starting the container"
    Rails.logger.info http_req(docker_obj.docker_host_fqdn,docker_obj.docker_host_api_key,docker_obj.docker_host_api_cert,'/containers/'+container_name+'/start',start_params)

    Rails.logger.info "Container status: "
    container_status= JSON.parse(http_req(docker_obj.docker_host_fqdn,docker_obj.docker_host_api_key,docker_obj.docker_host_api_cert,'/containers/'+container_name+'/json'))
    Rails.logger.info container_status

    container_status['Config']['Env'].each do |line|
      if /password/.match(line)
        line = line.gsub(/=.+/,'= *******')
      end
    end

    return container_status

  end

  def stop_container(running_test_obj,docker_obj)
    Rails.logger.info http_req(docker_obj.docker_host_fqdn,docker_obj.docker_host_api_key,docker_obj.docker_host_api_cert,"/containers/#{running_test_obj.container_name}/stop")
  end

  def http_req(docker_host_fqdn,docker_host_api_key,docker_host_api_cert,uri,req_params='')
    require 'net/https'
    https = Net::HTTP.new(docker_host_fqdn, 2376)
    https.use_ssl = true
    https.cert = OpenSSL::X509::Certificate.new(docker_host_api_cert) #File.read(Rails.root.join('docker_certs','cert.pem')))
    https.key = OpenSSL::PKey::RSA.new(docker_host_api_key) #Rails.root.join('docker_certs','key.pem')))
    https.verify_mode = OpenSSL::SSL::VERIFY_NONE
    https.read_timeout = 120
    https.start do |https|
      if req_params.is_a?(Hash)
        request = Net::HTTP::Post.new(uri,{"Content-Type": "application/json"})
        request.body=(req_params).to_json
      else
        request = Net::HTTP::Get.new(uri)
      end
      response = https.request(request)
#      response.value
      return response.body

    end
  end

end

app/views/dockers/edit.html.erb
<br>
<br>

<div class="new_resource_container">
  <div class="new_resource_caption">
    <p>Edit Docker host configuration</p>
  </div>

  <%= form_with model: @docker, local: true, method: "patch", :action => 'update' do |form| %>
    <table class="new_resource_table" border="none">
      <tr>
        <td>Docker host custom name</td>
        <td><%= form.text_field(:docker_host_name, :class=>"form_input", value: @docker.docker_host_name) %></td>
      </tr>
      <tr>
        <td>FQDN/IP address</td>
        <td><%= form.text_field(:docker_host_fqdn, :class=>"form_input", value: @docker.docker_host_fqdn) %></td>
      </tr>
      <tr>
        <td>RAM, GB</td>
        <td><%= form.text_field(:docker_host_ram, :class=>"form_input", value: @docker.docker_host_ram) %></td>
      </tr>
        <tr>
        <td>CPU, cores</td>
        <td><%= form.text_field(:docker_host_cpu, :class=>"form_input", value: @docker.docker_host_cpu) %></td>
      </tr>
        <tr>
        <td>Disk space, GB</td>
        <td><%= form.text_field(:docker_host_disk_space, :class=>"form_input", value: @docker.docker_host_disk_space) %></td>
      </tr>
        <tr>
        <td>Host geographic location</td>
        <td><%= form.text_field(:docker_host_location, :class=>"form_input", value: @docker.docker_host_location) %></td>
      </tr>
        <tr>
        <td>Network interface throughput, GBit/s</td>
        <td><%= form.text_field(:docker_host_network_interface_throughput, :class=>"form_input", value: @docker.docker_host_network_interface_throughput) %></td>
      </tr>
        <tr>
        <td>Host provider type</td>
        <td><%= form.select(:docker_host_provider_type, [['Bare metall', 'bare_metall'],['AWS', 'aws'], ['GCP', 'gcp'],['Azure', 'azure']],{value: @docker.docker_host_provider_type}, { :class=>'form_input' }) %></td>
      </tr>
        <tr>
        <td>Docker API client key (key.pem)</td>
        <td><%= form.text_area(:docker_host_api_key, size:"50x5", :class=>"form_input", value: @docker.docker_host_api_key) %></td>
      </tr>
        <tr>
        <td>Docker API certificate (cert.pem)</td>
        <td><%= form.text_area(:docker_host_api_cert, size:"50x5", :class=>"form_input", value: @docker.docker_host_api_cert) %></td>
      </tr>
    </table>
    <p>
      <%= form.submit("Update configuration",:class=>"form_button") %>
    </p>
  <% end %>
</div>

app/views/dockers/get_dh_images.html.erb
 
<div class="container">
  <table class="responsive-table">
    <caption><%= @docker.docker_host_fqdn %> docker hosts images list</caption>
    <thead>
       <tr>
          <th scope="col">Name</th>
          <th scope="col">Hash</th>
          <th scope="col">Creation date</th>
          <th scope="col">Size, MB</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <td></td>
      </tr>
    </tfoot>
    <tbody>
    <% @dh_images.each do |dh_image| %>
      <tr>
        <td data-title="Name"><%= dh_image["RepoTags"][0] %></td>
        <td data-title="Hash"><%= dh_image["Id"][7..14] %></td>
        <% dh_image_creation_date_obj=Time.at(dh_image["Created"]).utc.to_datetime %>
        <td data-title="Creation date"><%= dh_image_creation_date_obj.to_formatted_s(:rfc822) %></td>
        <td data-title="Size, MB"><%= (dh_image["Size"].to_f/1000000).round(2) %></td>
      </tr>
    <% end %>
     </tbody>
  </table>
</div>

app/views/dockers/index.html.erb
<div class="header">
  <%= link_to "Add Docker host", new_docker_path, class: "actions" %>
</div>

<div class="container">
  <table class="responsive-table">
    <caption>Available Docker hosts list</caption>
    <thead>
       <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">FQDN/IP</th>
          <th scope="col">RAM, GB</th>
          <th scope="col">CPU, cores</th>
          <th scope="col">Disk space, GB</th>
          <th scope="col">Location</th>
          <th scope="col">Network throughput, GB/s</th>
          <th scope="col">Provider</th>
          <th scope="col_action">Get available Images</th>
          <th scope="col_action">Edit host configuration</th>
          <th scope="col_action">Delete host</th>
          
      </tr>
    </thead>
    <tfoot>
      <tr>
        <td></td>
      </tr>
    </tfoot>
    <tbody>                  
      <% @dockers.each do |docker| %>
        <tr>
          <th scope="row"><%= link_to docker.id.to_s, docker_path(docker) %></th>
            <td data-title="Name"><%= docker.docker_host_name %></td>
            <td data-title="FQDN|IP"><%= docker.docker_host_fqdn %></td>
            <td data-title="RAM"><%= docker.docker_host_ram %></td>
            <td data-title="CPU"><%= docker.docker_host_cpu %></td>
            <td data-title="Disk space"><%= docker.docker_host_disk_space %></td>
            <td data-title="Location"><%= docker.docker_host_location %></td>
            <td data-title="Network throughput"><%= docker.docker_host_network_interface_throughput %></td>
            <td data-title="Provider"><%= docker.docker_host_provider_type %></td>
            <td data-title="Get images"><%= link_to 'Images', '/dockers/images?id='+docker.id.to_s  %></td>
            <td data-title="Edit"><%= link_to 'Edit', edit_docker_path(docker) %></td>
            <td data-title="Delete"><%= link_to 'Delete', docker_path(docker), method: :delete,
                          data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div> 

app/views/dockers/new.html.erb
<br>
<br>

<div class="new_resource_container">
  <div class="new_resource_caption">
    <p>Docker host configuration</p>
  </div>

    <%= form_with scope: :docker, url: dockers_path, local: true do |form| %>
      <table class="new_resource_table" border="none">
      <tr>
        <td>Docker host custom name</td>
        <td><%= form.text_field(:docker_host_name, :class=>"form_input", value:"Sample host") %></td>
      </tr>
      <tr>
        <td>FQDN/IP address</td>
        <td><%= form.text_field(:docker_host_fqdn, :class=>"form_input", value:"127.0.0.1") %></td>
      </tr>
      <tr>
        <td>RAM, GB</td>
        <td><%= form.text_field(:docker_host_ram, :class=>"form_input", value:2) %></td>
      </tr>
        <tr>
        <td>CPU, cores</td>
        <td><%= form.text_field(:docker_host_cpu, :class=>"form_input", value:2) %></td>
      </tr>
        <tr>
        <td>Disk space, GB</td>
        <td><%= form.text_field(:docker_host_disk_space, :class=>"form_input", value: 10) %></td>
      </tr>
        <tr>
        <td>Host geographic location</td>
        <td><%= form.text_field(:docker_host_location, :class=>"form_input", value:"localhost") %></td>
      </tr>
        <tr>
        <td>Network interface throughput, GBit/s</td>
        <td><%= form.text_field(:docker_host_network_interface_throughput, value:1, :class=>"form_input") %></td>
      </tr>
        <tr>
        <td>Host provider type</td>
        <td><%= form.select(:docker_host_provider_type, [['Bare metall', 'bare_metall'],['AWS', 'aws'], ['GCP', 'gcp'],['Azure', 'azure']],{}, { :class=>'form_input' }) %></td>
      </tr>
        <tr>
        <td>Docker API client key (key.pem)</td>
        <td><%= form.text_area(:docker_host_api_key, size:"50x5",:class=>"form_input", value:"Docker client key (key.pem) content. Check https://docs.docker.com/engine/security/https/ for more information ") %></td>
      </tr>
        <tr>
        <td>Docker API certificate (cert.pem)</td>
        <td><%= form.text_area(:docker_host_api_cert, size:"50x5",:class=>"form_input", value:"Docker client certificate (cert.pem) content. Check https://docs.docker.com/engine/security/https/ for more information ") %></td>
      </tr>
    </table>
    <p>
      <%= form.submit("Save configuration",:class=>"form_button") %>
    </p>
  <% end %>
</div>

app/views/dockers/schedule_test.html.erb
<div class="container">
    <table class="responsive-table">
      <caption>CD pipeline integration details</caption>
      <thead>
        <tr>
          <th scope="col">Path</th>
          <th scope="col">Parameters</th>
          <th scope="col">Description</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= dockers_schedule_test_path %></td>
          <td style="text-align:left">
            <pre>
             <!-- Begin of the JSON output -->
             <%= JSON.pretty_generate(@request_params)  %>
             <!-- End of the JSON output -->
            </pre></td>
          <td>Create and start Docker container</td>
        </tr>
      </tbody>
    </table>
</div>

<div class="container">
    <table class="responsive-table">
        <caption><%= @container_name %> Docker container details</caption>
        <tr>
          <td style="text-align:left; border:1px solid #1d96b2">
            <pre>
              <!-- Begin of the JSON output -->
              <%= JSON.pretty_generate(@test_attributes) %>
              <!-- End of the JSON output -->
            </pre>
          </td>
        </tr>
    </table>
</div>

app/views/dockers/show.html.erb
<br>
<br>

<div class="new_resource_container">
  <div class="new_resource_caption">
    <p>Docker hosts configuration summary</p>
  </div>


  <table class="new_resource_table" border="none">
      <tr>
        <td>ID</td>
        <td><%= @docker.id %></td>
      </tr>
      <tr>
        <td>Name</td>
        <td><%= @docker.docker_host_name %></td>
      </tr>
      <tr>
        <td>FQDN/IP</td>
        <td><%= @docker.docker_host_fqdn %></td>
      </tr>
      <tr>
        <td>RAM, GB</td>
        <td><%= @docker.docker_host_ram %></td>
      </tr>
      <tr>
        <td>CPU, cores</td>
        <td><%= @docker.docker_host_cpu %></td>
      </tr>
      <tr>
        <td>Disk space, GB</td>
        <td><%= @docker.docker_host_disk_space %></td>
      </tr>
      <tr>
        <td>Location</td>
        <td><%= @docker.docker_host_location %></td>
      </tr>
      <tr>
        <td>Network interface throughput, GBit/s</td>
        <td><%= @docker.docker_host_network_interface_throughput %></td>
      </tr>
      <tr>
        <td>Provider type</td>
        <td><%= @docker.docker_host_provider_type %></td>
      </tr>
      <tr>
        <td>Docker API key</td>
        <td><%= @docker.docker_host_api_key[30..55] %></td>
      </tr>
      <tr>
        <td>Docker API certificate</td>
        <td><%= @docker.docker_host_api_cert[25..50] %></td>
      </tr>
    </table>
    <%= link_to 'Back to the Docker hosts list', dockers_path, class: "header" %>
</div>